#!/bin/sh

# Use this script as your EDITOR to allow editing local files with emacsclient.
# Works by connecting to the local Emacs-server and opens file in new buffer.

emacsclient -n -s ~/.emacs.d/server/server $@
